[package]
name = "rsa_victim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autocfg = "1.1.0"
cfg-if = "1.0.0"
chrono = "0.4.31"
rand = "0.8.5"
rng = "0.1.0"
rsa = "0.9.2"
thread = "0.1.0"
